/**
 * Portfolio component
 *
 * Highlights some of  your creations. These can be designs, websites,
 * open source contributions, articles you've written and more.
 *
 * This is a great area for you to to continually add to and refine
 * as you continue to learn and create.
 */

import React from "react";

/**
 * Desk image
 *
 * Below is a sample desk image. Feel free to update this to an image of your choice,
 * updating below imageAltText to string that represents what you see in that image.
 *
 * Need an image? Check out https://unsplash.com to download a photo you
 * freely use on your site.
 */
import image from "../images/design-desk.jpeg";

const imageAltText = "desktop with books and laptop";

/**
 * Project list
 *
 * An array of objects that will be used to display for your project
 * links section. Below is a sample, update to reflect links you'd like to highlight.
 */
const projectList = [
  {
    title: "Wonderlust",
    description:
      "Welcome to our platform, your premier destination for finding the perfect rental property. Our platform offers a curated selection of diverse listings, ensuring that whether you're seeking a cozy s…",
    url: "https://wonderlust-aditya-kumar.onrender.com/",
  },
  {
    title: "E-commerce website",
    description:
      "This is a basic e-commerce website built using HTLM, CSS, JavaScript.",
    url: "https://e-commerce-website-kohl-three.vercel.app/",
  },
  {
    title: "Simon Say",
    description:
      "The Simon game is a memory game where players have to repeat a sequence of lights and sounds generated by the game.",
    url: "https://simon-game-theta-blush.vercel.app/",
  },
  {
    title: "sun-project",
    description:
      "This Repository shows how the Sun, Earth and Moon are connected to each other.",
    url: "https://sun-project-beige.vercel.app/",
  },
];

const Portfolio = () => {
  return (
    <section className="padding" id="portfolio">
      <h2 style={{ textAlign: "center" }}>Portfolio</h2>
      <div style={{ display: "flex", flexDirection: "row", paddingTop: "3rem" }}>
        <div style={{ maxWidth: "40%", alignSelf: "center" }}>
          <img
            src={image}
            style={{ height: "90%", width: "100%", objectFit: "cover" }}
            alt={imageAltText}
          />
        </div>
        <div className="container">
          {projectList.map((project) => (
            <div className="box" key={project.title}>
              <a href={project.url} target="_blank" rel="noopener noreferrer">
                <h3 style={{ flexBasis: "40px" }}>{project.title}</h3>
              </a>
              <p className="small">{project.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Portfolio;
